# Big Data for environmental sciences

## Exercises

We have time series data obtained from multiple sites. A common task is to complement our data with information about the sites (meta data), or with data from other sources and analyse it using this additional data. In this exercise, you will learn to...

### Overview

- **Input**: From the last session they learned how to look at two flux tower site of dataset 1.  
- **Output**: They have gotten familiar with the dataset 2, which contains multiple site 

**Content**

- Meta data
- Combining data: For our set of FLUXNET sites, collect data from other sources (global fields, remote sensing)
- Finding, accessing, downloading, and reading environmental data from the web, web scraping
- MODIS, Landsat, Google Earth Engine, Worldclim, Chelsa, CRU, (some re-analysis), CMIP5 from Urs, HWSD, ETOPO1, Biome classification, IGBP veg types, Koeppen-Geiger climate, …...
- Merging, nesting
- Formats: geo data: raster, NetCDF, CSV, shapefile
- bash, cron, wget, grep, system, RegExp

### Read multiple files

